spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/dimdimplus}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345678}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
          lob:
            '[non_contextual_creation]': true
    generate-ddl: true
