app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
        format_sql: true
